cloudflare/mcp-server-cloudflare

src/tools/analytics.ts, src/tools/d1.ts, src/tools/kv.ts, src/tools/r2.ts, src/tools/workers.ts
In our current implementation (e.g. in src/tools/workers.ts), handlers return responses with content nested under a toolResult property:
`worker_list: async (request) => {
const results = await handleWorkerList()
return {
toolResult: {
content: [
{
type: "text",
text: JSON.stringify(results, null, 2)
}
]
}
}
}`
However, Cursor expects the content array directly at the top level of the response object:
`worker_list: async (request) => {
const results = await handleWorkerList()
return {
content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
metadata: {}
}
}`
This PR updates all tool handlers to use the direct content format rather than nesting it under toolResult, making the MCP server compatible with Cursor.
=> Fix: Update tools to be compatible with Cursor and other MCP clients

.eslintrc.cjs, .vscode/extensions.json, .vscode/settings.json, apps/workers-observability/src/index.ts, apps/workers-observability/src/tools/account.ts, apps/workers-observability/src/tools/logs.ts, apps/workers-observability/src/tools/workers.ts, apps/workers-observability/types.d.ts, apps/workers-observability/vitest.config.ts, apps/workers-observability/wrangler.jsonc, packages/mcp-common/src/api/account.ts, packages/mcp-common/src/api/logs.ts, packages/mcp-common/src/api/workers.ts, packages/mcp-common/src/cloudflare-api.ts, packages/mcp-common/src/cloudflare-auth.ts, packages/mcp-common/src/cloudflare-oauth-handler.ts, packages/mcp-common/src/mcp-error.ts, packages/mcp-common/src/v4-api.ts, packages/mcp-common/tests/logs.spec.ts, packages/mcp-common/types.d.ts, packages/mcp-common/vitest.config.ts, packages/typescript-config/workers.json
Runs prettier formatter across all files
=> Run prettier formatter over all files

packages/mcp-common/src/utils/cloudflare-mock.ts, packages/mcp-common/tests/logs.spec.ts
Mocks the Cloudflare API client using vitest mock implementation.
We can't use fetchMock due to api client not working in vitest, but this should be a good enough way to mock things for our purposes.
We just need to remember to add whatever methods we're testing to this mockImplementation
=> Add initial mocks for Cloudflare api client

README.md, apps/sandbox-container/README.md, apps/sandbox-container/container/index.ts, apps/sandbox-container/package.json, apps/sandbox-container/server/index.ts, apps/sandbox-container/worker-configuration.d.ts, apps/sandbox-container/wrangler.jsonc, apps/workers-bindings/src/index.ts, apps/workers-bindings/worker-configuration.d.ts, apps/workers-bindings/wrangler.jsonc, apps/workers-observability/README.md, apps/workers-observability/package.json, apps/workers-observability/src/index.ts, apps/workers-observability/worker-configuration.d.ts, apps/workers-observability/wrangler.jsonc, packages/mcp-common/src/cloudflare-oauth-handler.ts, packages/mcp-common/src/config.ts, pnpm-lock.yaml
Moves observability server to it's own subdomain and introduces a shared "ENVIRONMENT" variable type across the different apps
=> Move observability server to it's own subdomain

apps/workers-bindings/package.json, apps/workers-bindings/src/index.ts, apps/workers-bindings/wrangler.jsonc, packages/mcp-common/src/tools/r2_bucket.ts, packages/mcp-common/src/types/r2_bucket.ts
This pull request adds tools for managing R2 buckets including,
accounts_list
List all accounts in your Cloudflare account
set_active_account
Set active account to be used for tool calls that require accountId
kv_namespaces_list
List all of the kv namespaces in your Cloudflare account
kv_namespace_create
Create a new kv namespace in your Cloudflare account
kv_namespace_delete
Delete a kv namespace in your Cloudflare account
kv_namespace_get
Get a kv namespace in your Cloudflare account
kv_namespace_update
Update a kv namespace in your Cloudflare account
workers_list
List all Workers in your Cloudflare account
worker_get_worker
Get the source code of a Cloudflare Worker
r2_buckets_list
List all of the r2 buckets in your Cloudflare account
r2_bucket_create
Create a new r2 bucket in your …
=> feat: add r2 tools to bindings mcp

apps/sandbox-container/server/index.ts, apps/workers-bindings/src/index.ts, apps/workers-observability/src/index.ts, packages/mcp-common/src/cloudflare-auth.ts, packages/mcp-common/src/cloudflare-oauth-handler.ts
Don't use DefaultScopes for `/oauth/authorize` endpoint, instead have each app define it's own scopes
=> Have each app define it's own scopes

.vscode/launch.json, apps/workers-bindings/src/index.ts, apps/workers-observability/src/index.ts
This PR fixes an issue where we were having to set the active account id twice when the MCP Server. The reason the bug was happening is as follows
Here's the flow:
1. Define an McpAgent with an initialState property [like so](https://github.com/cloudflare/mcp-server-cloudflare/blob/main/apps/workers-bindings/src/index.ts#L34-L36)
2. Call the [setActiveAccountId tool](https://github.com/cloudflare/mcp-server-cloudflare/blob/main/packages/mcp-common/src/tools/account.ts#L65)
3. Spread this.state into the [setState call](https://github.com/cloudflare/mcp-server-cloudflare/blob/main/apps/workers-bindings/src/index.ts#L58)
4. this.state calls the getter which passes through to [this.#agent.state getter](https://github.com/cloudflare/agents/blob/main/packages/agents/src/mcp/index.ts#L226)
5. …
=> fix: set account id issue and add debugger config

.dockerignore, apps/sandbox-container/Dockerfile, apps/sandbox-container/package.json
Updated the original Dockerfile for the container MCP server to work with the new monorepo setup
1. Base off a node image rather than ubuntu to simplify node installation side effects
2. Swap npm to pnpm
3. Separate the installation of ca-certificates from the other packages, because for whatever reason that seemed to get it to stop erroring on installation
4. Install all python libraries as apt packages to avoid error
5. Add turbo pruning to keep the lock file limited to only the needed packages for running the sandbox container 
6. Adjust build command to incorporate other needed files in the monorepo
=> Update container server Dockerfile to work with monorepo

apps/docs-autorag/src/context.ts, apps/sandbox-container/server/context.ts, apps/sandbox-container/server/index.ts, apps/workers-bindings/src/context.ts, apps/workers-bindings/src/index.ts, apps/workers-bindings/wrangler.jsonc, apps/workers-observability/src/context.ts, apps/workers-observability/src/index.ts, apps/workers-observability/src/tools/logs.ts, apps/workers-observability/wrangler.jsonc, packages/mcp-common/src/durable-kv-store.ts, packages/mcp-common/src/durable-objects/user_details.ts, packages/mcp-common/src/env.ts, packages/mcp-common/src/scopes.ts, packages/mcp-common/src/sentry.ts, packages/mcp-common/src/tools/account.ts, packages/mcp-common/src/tools/d1.ts, packages/mcp-common/src/tools/kv_namespace.ts, packages/mcp-common/src/tools/r2_bucket.ts, packages/mcp-common/src/tools/worker.ts, packages/mcp-common/src/types/cloudflare-mcp-agent.ts
Introduces a new "UserDetails" Durable Object for persisting UserDetails in DO storage across sessions based off the userId
=> Persist activeAccountId in UserDetails DO so we can persist activeAccountId selection across sessions

apps/docs-autorag/src/context.ts, apps/sandbox-container/server/context.ts, apps/workers-bindings/src/context.ts, apps/workers-bindings/src/index.ts, apps/workers-bindings/wrangler.jsonc, apps/workers-observability/src/context.ts, apps/workers-observability/src/index.ts, apps/workers-observability/src/tools/logs.ts, apps/workers-observability/wrangler.jsonc, packages/mcp-common/src/durable-kv-store.ts, packages/mcp-common/src/durable-objects/user_details.ts, packages/mcp-common/src/env.ts, packages/mcp-common/src/tools/account.ts, packages/mcp-common/src/tools/d1.ts, packages/mcp-common/src/tools/kv_namespace.ts, packages/mcp-common/src/tools/r2_bucket.ts, packages/mcp-common/src/tools/worker.ts, packages/mcp-common/src/types/cloudflare-mcp-agent.ts
Same as https://github.com/cloudflare/mcp-server-cloudflare/pull/81, just forgot to change targeting branch to main
=> Persist activeAccountId in UserDetails DO so we can persist activeAccountId selection across sessions 

implementation-guides/evals.md, implementation-guides/tools.md, implementation-guides/type-validators.md
This PR adds a few implementation guides for the major pieces of our MCP Servers to help people get up to speed:
- evals
- tools
- types and validators
These guides are especially useful if you reference them when developing with AI (e.g. "review how to write evals in @evals.ts and then create evals for this server..."). 
The implementation guides were created by feeding our existing code to Gemini along with a few best practices. Please suggest improvements if you've found other useful techniques 🙏
=> feat: add implementation guides to assist in AI-driven development

apps/docs-autorag/src/index.ts, apps/docs-autorag/wrangler.jsonc, apps/docs-vectorize/.eslintrc.cjs, apps/docs-vectorize/README.md, apps/docs-vectorize/package.json, apps/docs-vectorize/src/context.ts, apps/docs-vectorize/src/index.ts, apps/docs-vectorize/src/tools/docs.ts, apps/docs-vectorize/tsconfig.json, apps/docs-vectorize/vitest.config.ts, apps/docs-vectorize/worker-configuration.d.ts, apps/docs-vectorize/wrangler.jsonc, pnpm-lock.yaml
An alternative to the AutoRAG approach
=> Add a docs server based on the AI Assistant Vectorize index

packages/mcp-common/src/tools/account.ts
Users with a lot of accounts are wasting a lot of llm tokens on unused information, this pr makes sure only required (id + name) fields are returned to the LLM
=> Remove unused fields from list accounts mcp tool

apps/radar/README.md, apps/workers-bindings/CONTRIBUTING.md, apps/workers-bindings/README.md
Add a user-friendly readme for the workers bindings mcp server
=> feat: update README for workers-bindings mcp

apps/workers-bindings/evals/hyperdrive.eval.ts, packages/mcp-common/src/tools/hyperdrive.ts
Creating Hyperdrive configurations requires the user to pass their database's password. For now, this means that sensitive data ends up exposed to the LLM, the MCP Server, and the MCP Client. There is not consensus about how to handle sensitive data yet, so we're removing this tool until there is a standard.
=> chore: remove hyperdrive create tool

apps/radar/README.md, apps/radar/src/context.ts, apps/radar/src/tools/radar.ts, apps/radar/src/types/radar.ts, apps/radar/src/utils.ts
Add tools to retrieve information about:
- Layer 3 attacks
- Internet services ranking
- Internet speed
- DNS
- Email Routing
- Email Security
Created the `resolveAndInvoke` function to resolve and invoke a method from the TS library dynamically based on the provided slugs. This is useful for Radar because, for each dataset, we have many different endpoints (one for each dimension and data format). This approach allows us to create only one tool per dataset, as creating a tool for each endpoint seems excessive. I'm not sure if this is the best approach, and I'm open to suggestions on how to improve it. Also, I tried to improve the typing for that method, but I'm having a hard time.
=> Add more Radar tools

apps/radar/README.md, apps/radar/src/tools/radar.ts, apps/radar/src/types/radar.ts
Add more Radar tools:
- `get_ai_data`: Retrieves AI-related data, including traffic from AI user agents, as well as popular models and model tasks
- `get_internet_quality_data`: Retrieves a summary or time series of bandwidth, latency, or DNS response time from the Radar Internet Quality Index
=> Add AI and Internet quality Radar tools

.github/workflows/evals.yml, apps/sandbox-container/evals/utils.ts, apps/sandbox-container/package.json, apps/sandbox-container/server/containerMcp.ts, apps/sandbox-container/server/context.ts, apps/sandbox-container/server/index.ts, apps/sandbox-container/wrangler.jsonc, apps/workers-bindings/evals/utils.ts
There was an issue with the containers evals. I fixed the evals and got dev mode in sync with the other folders in the repo
=> Fix evals in CI

.changeset/new-zebras-relax.md, .github/workflows/branches.yml, apps/workers-observability/wrangler.jsonc
A bad entrypoint slipped through because we don't do `wrangler deploy --dry-run` for branches, so I added a branch job to do it.
Also fixed the entrypoint issue that this would have caught.
=> chore: add job to build Workers for branches and fix entrypoint

apps/docs-vectorize/src/docs-vectorize.app.ts, apps/docs-vectorize/src/prompts/docs-vectorize.prompts.ts, apps/docs-vectorize/src/tools/docs-vectorize.tools.ts
This adds the prompt from https://developers.cloudflare.com/workers/prompt.txt and lays the groundwork for any extra prompts we want to add
=> Add (detailed) prompt to docs-vectorize server

README.md
Explain how to generate a **user** API token and provide it to the OpenAI responses API.
=> Add OpenAI Responses API to readme

.changeset/long-spies-peel.md, apps/docs-vectorize/src/docs-vectorize.app.ts, apps/workers-bindings/src/bindings.app.ts, apps/workers-bindings/src/bindings.context.ts, apps/workers-bindings/wrangler.jsonc, apps/workers-observability/src/workers-observability.app.ts, apps/workers-observability/src/workers-observability.context.ts, apps/workers-observability/wrangler.jsonc, packages/mcp-common/src/prompts/docs-vectorize.prompts.ts, packages/mcp-common/src/tools/docs-vectorize.tools.ts, packages/mcp-common/src/types/cloudflare-mcp-agent.types.ts
Addresses #186 
Tested docs tools in observability-staging here:
and tested docs tools in bindings-staging here:
=> Add search docs tool to bindings and obs servers

.changeset/dirty-days-crash.md, packages/mcp-common/src/types/workers-logs.types.ts, packages/mcp-common/src/utils.spec.ts, packages/mcp-common/src/utils.ts
llms suck at time, so this tries to make it a little easier for them by letting them specific relative timeframes instead, consisting of a reference time and an offset in a semantic format (e.g. -5d12h30m)
also cleans up the examples to specify ISO time w/o timezone or ms
=> add relative timeframe support for querying workers observability data
